// lib/github-integration.ts
// GitHub Auto Pull Request Service for CyberSentry AI

export interface PatchFile {
  path: string
  originalContent: string
  patchedContent: string
}

export interface VulnerabilityInfo {
  name: string
  severity: string
  description: string
  fix: string
  cvss?: number
  cwe?: string
}

export interface PRResult {
  success: boolean
  prUrl?: string
  prNumber?: number
  branchName?: string
  error?: string
}

export interface PRConfig {
  owner: string        // e.g. "nischay908"
  repo: string         // e.g. "secure-ai"
  token: string        // GitHub Personal Access Token from env
  baseBranch?: string  // default: "main"
}

/* ─────────────────────────────────────────────────
   HELPER: GitHub REST API fetch wrapper
───────────────────────────────────────────────── */
async function githubFetch(
  path: string,
  token: string,
  method = 'GET',
  body?: object
) {
  const res = await fetch(`https://api.github.com${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
      'X-GitHub-Api-Version': '2022-11-28',
    },
    body: body ? JSON.stringify(body) : undefined,
  })

  if (!res.ok) {
    const err = await res.json().catch(() => ({ message: res.statusText }))
    throw new Error(`GitHub API ${method} ${path} failed: ${err.message}`)
  }

  return res.json()
}

/* ─────────────────────────────────────────────────
   STEP 1: Get latest commit SHA from base branch
───────────────────────────────────────────────── */
async function getLatestCommitSha(config: PRConfig): Promise<string> {
  const data = await githubFetch(
    `/repos/${config.owner}/${config.repo}/git/ref/heads/${config.baseBranch || 'main'}`,
    config.token
  )
  return data.object.sha
}

/* ─────────────────────────────────────────────────
   STEP 2: Create a new branch from latest SHA
───────────────────────────────────────────────── */
export async function createBranch(
  config: PRConfig,
  branchName: string
): Promise<string> {
  const sha = await getLatestCommitSha(config)

  await githubFetch(
    `/repos/${config.owner}/${config.repo}/git/refs`,
    config.token,
    'POST',
    {
      ref: `refs/heads/${branchName}`,
      sha,
    }
  )

  return branchName
}

/* ─────────────────────────────────────────────────
   STEP 3: Commit patched files to the new branch
───────────────────────────────────────────────── */
export async function commitPatch(
  config: PRConfig,
  branchName: string,
  files: PatchFile[],
  vulnerability: VulnerabilityInfo
): Promise<string> {
  // Get the latest tree SHA
  const branchData = await githubFetch(
    `/repos/${config.owner}/${config.repo}/git/ref/heads/${branchName}`,
    config.token
  )
  const latestSha = branchData.object.sha

  const commitData = await githubFetch(
    `/repos/${config.owner}/${config.repo}/git/commits/${latestSha}`,
    config.token
  )
  const baseTreeSha = commitData.tree.sha

  // Create blobs for each patched file
  const treeItems = await Promise.all(
    files.map(async (file) => {
      const blob = await githubFetch(
        `/repos/${config.owner}/${config.repo}/git/blobs`,
        config.token,
        'POST',
        {
          content: Buffer.from(file.patchedContent).toString('base64'),
          encoding: 'base64',
        }
      )
      return {
        path: file.path,
        mode: '100644',
        type: 'blob',
        sha: blob.sha,
      }
    })
  )

  // Create a new tree
  const newTree = await githubFetch(
    `/repos/${config.owner}/${config.repo}/git/trees`,
    config.token,
    'POST',
    {
      base_tree: baseTreeSha,
      tree: treeItems,
    }
  )

  // Create the commit
  const newCommit = await githubFetch(
    `/repos/${config.owner}/${config.repo}/git/commits`,
    config.token,
    'POST',
    {
      message: `security: patch ${vulnerability.name} (CVSS ${vulnerability.cvss || 'N/A'})`,
      tree: newTree.sha,
      parents: [latestSha],
    }
  )

  // Update the branch to point to the new commit
  await githubFetch(
    `/repos/${config.owner}/${config.repo}/git/refs/heads/${branchName}`,
    config.token,
    'PATCH',
    { sha: newCommit.sha }
  )

  return newCommit.sha
}

/* ─────────────────────────────────────────────────
   STEP 4: Create the Pull Request
───────────────────────────────────────────────── */
export async function createPullRequest(
  config: PRConfig,
  branchName: string,
  vulnerability: VulnerabilityInfo,
  files: PatchFile[]
): Promise<PRResult> {
  const fileList = files.map((f) => `- \`${f.path}\``).join('\n')

  const body = `## 🔒 Security Fix: ${vulnerability.name}

> **Auto-generated by [CyberSentry AI](https://secure-ai-livid.vercel.app)** — AI-powered vulnerability scanner & patcher.

---

### 🚨 Detected Vulnerability

| Field | Value |
|-------|-------|
| **Type** | ${vulnerability.name} |
| **Severity** | ${vulnerability.severity.toUpperCase()} |
| **CVSS Score** | ${vulnerability.cvss || 'N/A'} |
| **CWE** | ${vulnerability.cwe || 'N/A'} |

**Description:**
${vulnerability.description}

---

### 📁 Files Patched

${fileList}

---

### ✅ Fix Applied

${vulnerability.fix}

---

### 🔬 Verification Checklist

- [x] Parameterized queries replacing string concatenation
- [x] No user input directly interpolated into SQL/commands
- [x] Input validation added where missing
- [x] Security regression tests recommended

---

*This PR was automatically generated by CyberSentry AI. Please review the changes before merging.*`

  const pr = await githubFetch(
    `/repos/${config.owner}/${config.repo}/pulls`,
    config.token,
    'POST',
    {
      title: `🔒 Security Fix: ${vulnerability.name} Patch`,
      body,
      head: branchName,
      base: config.baseBranch || 'main',
      draft: false,
    }
  )

  return {
    success: true,
    prUrl: pr.html_url,
    prNumber: pr.number,
    branchName,
  }
}

/* ─────────────────────────────────────────────────
   MAIN: Full pipeline — scan → patch → PR
───────────────────────────────────────────────── */
export async function createSecurityPR(
  vulnerability: VulnerabilityInfo,
  files: PatchFile[]
): Promise<PRResult> {
  // Get config from environment variables
  const token = process.env.GITHUB_TOKEN
  const owner = process.env.GITHUB_OWNER
  const repo = process.env.GITHUB_REPO

  if (!token || !owner || !repo) {
    return {
      success: false,
      error: 'Missing GitHub environment variables: GITHUB_TOKEN, GITHUB_OWNER, GITHUB_REPO',
    }
  }

  const config: PRConfig = { token, owner, repo, baseBranch: 'main' }

  try {
    // Generate unique branch name
    const timestamp = Date.now()
    const safeName = vulnerability.name
      .toLowerCase()
      .replace(/[^a-z0-9]/g, '-')
      .replace(/-+/g, '-')
      .slice(0, 30)
    const branchName = `cybersentry/fix-${safeName}-${timestamp}`

    // Step 1: Create branch
    await createBranch(config, branchName)

    // Step 2: Commit patched files
    await commitPatch(config, branchName, files, vulnerability)

    // Step 3: Open PR
    const result = await createPullRequest(config, branchName, vulnerability, files)

    return result
  } catch (err: any) {
    return {
      success: false,
      error: err.message || 'Unknown error creating PR',
    }
  }
}